export interface Lab {
  slug: string;
  name: string;
  icon: string;
  gradient: string;
  tagline: string;
  taglineEn: string;
  description: string;
  descriptionEn: string;
  longDesc: string;
  longDescEn: string;
  status: 'active' | 'beta' | 'archived' | 'concept';
  tech: string[];
  github?: string;
  link?: string;
  usedBy?: { name: string; url?: string }[];
  features: string[];
  featuresEn: string[];
  version: string;
  contributors: string[];
}

export const LABS: Lab[] = [
  {
    slug: 'tyrolium-ui',
    name: 'Tyrolium UI',
    icon: 'ri-layout-masonry-line',
    gradient: 'linear-gradient(135deg, #0533c8 0%, #bf0000 100%)',
    tagline: 'Bibliothèque de composants Angular partagée',
    taglineEn: 'Shared Angular component library',
    description: 'Librairie Angular interne partagée par tous les sites du groupe. Navbar universelle, Auth, CTA, Footer, thèmes et langues.',
    descriptionEn: 'Internal Angular library shared across all group sites. Universal navbar, Auth, CTA, Footer, themes and languages.',
    longDesc: `Tyrolium UI est la bibliothèque de composants Angular développée en interne et partagée entre tous les projets du groupe Tyrolium. Elle fournit la navbar universelle avec gestion des thèmes (clair/sombre/auto), des langues (FR/EN) et du menu d'applications Tyrolium, le composant CTA, le footer, la modal d'authentification Useritium, plusieurs directives utilitaires (gloss effect) et les services de thème et langue. Construite avec Angular standalone components, elle garantit une cohérence visuelle parfaite sur l'ensemble de l'écosystème.`,
    longDescEn: `Tyrolium UI is an internally developed Angular component library shared across all Tyrolium group projects. It provides the universal navbar with theme (light/dark/auto), language (FR/EN) and Tyrolium apps menu management, the CTA component, footer, Useritium authentication modal, several utility directives (gloss effect) and theme/language services. Built with Angular standalone components, it ensures perfect visual consistency across the entire ecosystem.`,
    status: 'active',
    tech: ['Angular', 'TypeScript', 'CSS'],
    github: 'https://github.com/TheMaxium69/Tyrolium-UI',
    usedBy: [
      { name: 'tyrolium.fr',     url: 'https://tyrolium.fr' },
      { name: 'solidserv.fr',    url: 'https://solidserv.fr' },
      { name: 'tyroserv.fr',     url: 'https://tyroserv.fr' },
      { name: 'tyrociel.fr',     url: 'https://tyrociel.fr' },
      { name: 'gamenium.fr',     url: 'https://gamenium.fr' },
      { name: 'useritium.fr',    url: 'https://useritium.fr' },
      { name: 'nexiumiacrm.fr',  url: 'https://nexiumiacrm.fr' },
      { name: 'influnias.fr',    url: 'https://influnias.fr' },
      { name: 'vturias.fr',      url: 'https://vturias.fr' },
    ],
    version: 'V1.0',
    contributors: ['Maxime Tournier'],
    features: [
      'Navbar universelle (thème, langues, apps)',
      'Composants standalone Angular',
      'CTA, Footer, Auth Modal',
      'Service de thème dark/light/auto',
      'Service de langue FR/EN',
      'Directive Gloss Effect',
    ],
    featuresEn: [
      'Universal navbar (theme, languages, apps)',
      'Angular standalone components',
      'CTA, Footer, Auth Modal',
      'Dark/light/auto theme service',
      'FR/EN language service',
      'Gloss Effect directive',
    ],
  },
  {
    slug: 'tyrositeframework',
    name: 'TyroSiteFramework',
    icon: 'ri-code-s-slash-line',
    gradient: 'linear-gradient(135deg, #0533c8 0%, #bf0000 100%)',
    tagline: 'Framework PHP pour sites clients ultra-rapides',
    taglineEn: 'PHP framework for lightning-fast client websites',
    description: 'Framework PHP interne conçu pour développer des sites et applications web clients très rapidement, avec un système de composants réutilisables et des imports automatisés.',
    descriptionEn: 'Internal PHP framework designed to build client websites and web applications very quickly, with reusable components and automated imports.',
    longDesc: `TyroSiteFramework est le framework PHP interne de Tyrolium, pensé avant tout pour produire des sites et applications web clients de façon rapide et structurée. Son principe central repose sur un système de composants .phtml réutilisables avec imports automatisés, ce qui permet de construire une page entière en assemblant des briques sans configuration fastidieuse. Le routing par identifiants de page simplifie la navigation, tandis que le système d'extensions modulaire permet d'ajouter des fonctionnalités au cas par cas. Il peut également exposer des endpoints API, mais c'est le développement de sites web pour les clients de Tyrolium qui reste son usage principal. Zéro dépendance externe, contrôle total du code.`,
    longDescEn: `TyroSiteFramework is Tyrolium's internal PHP framework, designed primarily to build client websites and web applications quickly and in a structured way. Its core principle is a reusable .phtml component system with automated imports, making it possible to build a full page by assembling blocks without tedious configuration. Page ID-based routing simplifies navigation, while the modular extension system allows features to be added on a per-project basis. It can also expose API endpoints, but building websites for Tyrolium's clients remains its primary use case. Zero external dependencies, full code control.`,
    status: 'active',
    tech: ['PHP', 'MySQL', 'No-dependency'],
    github: 'https://github.com/TheMaxium69/TyroSiteFrameWork',
    usedBy: [
      { name: 'dashboard.useritium.fr', url: 'https://dashboard.useritium.fr' },
      { name: 'batirpositif.fr',  url: 'https://batirpositif.fr' },
      { name: 'cls-habitat.fr',   url: 'https://www.cls-habitat.fr/' },
      { name: 'maximetournier.fr', url: 'https://maximetournier.fr' },
      { name: 'avra-formules.fr', url: 'https://story.avra.tyrolium.fr/' },
    ],
    version: 'V2.0',
    contributors: ['Maxime Tournier'],
    features: [
      'Composants .phtml réutilisables avec imports automatisés',
      'Développement de sites clients ultra-rapide',
      'Routing basé sur des IDs de page',
      'Système d\'extensions modulaire',
      'Zéro dépendance externe',
      'Support API REST en option',
    ],
    featuresEn: [
      'Reusable .phtml components with automated imports',
      'Ultra-fast client website development',
      'Page ID-based routing',
      'Modular extension system',
      'Zero external dependencies',
      'Optional REST API support',
    ],
  },
  {
    slug: 'api-getserver-minecraft',
    name: 'ApiGetServer for Minecraft',
    icon: 'ri-server-line',
    gradient: 'linear-gradient(135deg, #0533c8 0%, #bf0000 100%)',
    tagline: 'API PHP pour exposer les données d\'un serveur Minecraft',
    taglineEn: 'PHP API to expose Minecraft server data externally',
    description: 'API PHP hébergée sur le même serveur que Minecraft, permettant d\'exposer à l\'extérieur les données clés : joueurs connectés, stats, map, et intégration des plugins majeurs.',
    descriptionEn: 'PHP API hosted on the same server as Minecraft, exposing key data externally: connected players, stats, map info and integration with major plugins.',
    longDesc: `ApiGetServer for Minecraft est une API PHP conçue pour communiquer avec un serveur Minecraft hébergé sur la même machine. Elle permet d'exposer à l'extérieur des informations importantes comme le nombre de joueurs connectés, les statistiques par joueur ou les données de la map. Elle s'intègre également avec les plugins Minecraft les plus courants - EssentialsX, LuckPerms, le plugin Factions et TyroPlugin - en lisant directement leurs fichiers .json et .db. Compatible avec les plateformes Bukkit, Spigot et Paper, elle sert de pont entre l'infrastructure Minecraft et les applications web externes.`,
    longDescEn: `ApiGetServer for Minecraft is a PHP API designed to communicate with a Minecraft server hosted on the same machine. It exposes key information externally, such as the number of connected players, per-player statistics and map data. It also integrates with the most common Minecraft plugins - EssentialsX, LuckPerms, the Factions plugin and TyroPlugin - by directly reading their .json and .db files. Compatible with Bukkit, Spigot and Paper, it acts as a bridge between the Minecraft infrastructure and external web applications.`,
    status: 'active',
    tech: ['PHP', 'JSON', 'SQLite'],
    github: 'https://github.com/TheMaxium69/Api-GetServerMinecraft',
    usedBy: [
      { name: 'TyroServ',   url: 'https://tyroserv.fr' },
      { name: 'TyroPlugin', url: 'https://github.com/TheMaxium69/TyroPlugin' },
      { name: 'Launcher de TyroServ', url: 'https://github.com/TheMaxium69/Launcher-TyroServS3' },
    ],
    version: 'V1.0',
    contributors: ['Maxime Tournier'],
    features: [
      'Nombre de joueurs connectés en temps réel',
      'Statistiques par joueur',
      'Informations sur la map',
      'Intégration EssentialsX, LuckPerms, Factions',
      'Intégration TyroPlugin',
      'Compatible Bukkit / Spigot / Paper',
    ],
    featuresEn: [
      'Real-time connected player count',
      'Per-player statistics',
      'Map information',
      'EssentialsX, LuckPerms, Factions integration',
      'TyroPlugin integration',
      'Compatible with Bukkit / Spigot / Paper',
    ],
  },
  {
    slug: 'genjson-minecraft',
    name: 'GenJSON for Minecraft',
    icon: 'ri-braces-line',
    gradient: 'linear-gradient(135deg, #0533c8 0%, #bf0000 100%)',
    tagline: 'Générateur automatique de fichiers JSON pour mods Minecraft',
    taglineEn: 'Automatic JSON file generator for Minecraft mods',
    description: 'Script PowerShell qui génère automatiquement les fichiers JSON de ressources Minecraft - blockstates, modèles d\'items et de blocs - pour accélérer le développement de mods.',
    descriptionEn: 'PowerShell script that automatically generates Minecraft resource JSON files - blockstates, item and block models - to speed up mod development.',
    longDesc: `GenJSON for Minecraft est un script PowerShell conçu pour automatiser la génération des fichiers JSON de ressources nécessaires au développement de mods Minecraft. Créer manuellement les fichiers blockstates, les modèles d'items et de blocs pour chaque élément d'un mod est une tâche répétitive et fastidieuse. GenJSON prend en charge cette génération automatiquement à partir d'une configuration simple, pour produire en masse l'ensemble des fichiers JSON conformes aux spécifications de Minecraft. Utilisé en production pour TyroServ et TyroMod.`,
    longDescEn: `GenJSON for Minecraft is a PowerShell script designed to automate the generation of resource JSON files required for Minecraft mod development. Manually creating blockstate files, item models and block models for every element in a mod is a repetitive and time-consuming task. GenJSON handles this generation automatically from a simple configuration, mass-producing all JSON files in line with Minecraft's specifications. Used in production for TyroServ and TyroMod.`,
    status: 'beta',
    tech: ['PowerShell'],
    github: 'https://github.com/TheMaxium69/generatedJsonMinecraftMod',
    usedBy: [
      { name: 'TyroServ', url: 'https://tyroserv.fr' },
      { name: 'TyroMod',  url: 'https://github.com/TheMaxium69/TyroMod' },
    ],
    version: 'V0.2-beta',
    contributors: ['Maxime Tournier'],
    features: [
      'Génération automatique des fichiers blockstates',
      'Génération des modèles d\'items (.json)',
      'Génération des modèles de blocs (.json)',
      'Génération en masse depuis une configuration simple',
      'Aucune dépendance externe (PowerShell natif)',
      'Compatible Minecraft Forge uniquement',
    ],
    featuresEn: [
      'Automatic blockstate file generation',
      'Item model generation (.json)',
      'Block model generation (.json)',
      'Bulk generation from a simple configuration',
      'No external dependencies (native PowerShell)',
      'Minecraft Forge only',
    ],
  },
  {
    slug: 'tyrogit',
    name: 'TyroGit Client',
    icon: 'ri-git-repository-line',
    gradient: 'linear-gradient(135deg, #0533c8 0%, #bf0000 100%)',
    tagline: 'Client Git visuel avec intégration de thèmes',
    taglineEn: 'Visual Git client with theme integration',
    description: 'Alternative à GitHub Desktop développée en interne, avec support multi-remote, logos de dépôt personnalisés via .tyrogit et intégration des thèmes Tyrolium.',
    descriptionEn: 'An internally developed alternative to GitHub Desktop, with multi-remote support, custom repository logos via .tyrogit and Tyrolium theme integration.',
    longDesc: `TyroGit Client est le client Git de bureau de Tyrolium, conçu comme une alternative à GitHub Desktop. Il se connecte aux principaux hébergeurs Git - GitHub, GitLab et repo.tyrolium.fr - avec un support multi-remote natif sur un même dépôt. Sa particularité : la prise en charge des fichiers .tyrogit, qui permettent d'associer un logo et une identité visuelle à chaque dépôt directement dans l'interface. Construit avec Electron.js, il embarque une intégration complète des thèmes clair et sombre pour une expérience cohérente avec l'écosystème Tyrolium.`,
    longDescEn: `TyroGit Client is Tyrolium's desktop Git client, designed as an alternative to GitHub Desktop. It connects to the main Git providers - GitHub, GitLab and repo.tyrolium.fr - with native multi-remote support on a single repository. Its standout feature: .tyrogit file support, which lets you associate a logo and visual identity with each repository directly in the interface. Built with Electron.js, it includes full light and dark theme integration for an experience consistent with the Tyrolium ecosystem.`,
    status: 'beta',
    tech: ['Electron.js', 'Node.js', 'Git'],
    github: 'https://github.com/TheMaxium69/TyroGit',
    version: 'V0.1-beta',
    contributors: ['Maxime Tournier'],
    features: [
      'Interface visuelle type GitHub Desktop',
      'Logos de dépôt personnalisés via .tyrogit',
      'Support multi-remote natif',
      'Compatible GitHub, GitLab, repo.tyrolium.fr',
      'Intégration thèmes clair/sombre',
      'Gestion des dépôts locaux et distants',
    ],
    featuresEn: [
      'GitHub Desktop-style visual interface',
      'Custom repository logos via .tyrogit',
      'Native multi-remote support',
      'Compatible with GitHub, GitLab, repo.tyrolium.fr',
      'Light/dark theme integration',
      'Local and remote repository management',
    ],
  },
  {
    slug: 'discordbot-framework',
    name: 'DiscordBot Framework',
    icon: 'ri-discord-line',
    gradient: 'linear-gradient(135deg, #0533c8 0%, #bf0000 100%)',
    tagline: 'Framework Java pour créer des bots Discord rapidement',
    taglineEn: 'Java framework for building Discord bots fast',
    description: 'Framework interne basé sur JDA Discord qui permet à Tyrolium de développer des bots Discord rapidement pour ses filiales et ses clients.',
    descriptionEn: 'Internal framework built on JDA Discord that lets Tyrolium develop Discord bots quickly for its subsidiaries and clients.',
    longDesc: `DiscordBot Framework est la base commune utilisée chez Tyrolium pour créer des bots Discord en Java via JDA (Java Discord API). Il abstrait la configuration initiale, la gestion des commandes et les événements Discord pour permettre de démarrer un nouveau bot en quelques minutes. Conçu pour être réutilisé sur l'ensemble de l'écosystème Tyrolium - filiales et projets clients - il est actuellement à la base de TyroBot, TyroServBot et SolidServBot.`,
    longDescEn: `DiscordBot Framework is the shared foundation used at Tyrolium to build Discord bots in Java via JDA (Java Discord API). It abstracts initial setup, command handling and Discord events to allow a new bot to be started in minutes. Designed for reuse across the entire Tyrolium ecosystem - subsidiaries and client projects - it currently powers TyroBot, TyroServBot and SolidServBot.`,
    status: 'active',
    tech: ['Java', 'JDA', 'Discord'],
    github: 'https://github.com/TheMaxium69/DiscordBotFrameWork',
    usedBy: [
      { name: 'TyroBot',      url: 'https://github.com/TheMaxium69/TyroBotDiscord' },
      { name: 'TyroServBot',  url: 'https://github.com/TheMaxium69/TyroServBotDiscord' },
      { name: 'SolidServBot', url: 'https://github.com/TheMaxium69/SolidServ-Bot' },
    ],
    version: 'V1.0',
    contributors: ['Maxime Tournier'],
    features: [
      'Base commune pour bots Discord en Java',
      'Intégration JDA (Java Discord API)',
      'Gestion des commandes slash et préfixées',
      'Gestion des événements Discord',
      'Démarrage d\'un nouveau bot en quelques minutes',
      'Réutilisable sur l\'ensemble de l\'écosystème Tyrolium',
    ],
    featuresEn: [
      'Shared foundation for Java Discord bots',
      'JDA (Java Discord API) integration',
      'Slash and prefix command handling',
      'Discord event management',
      'New bot up and running in minutes',
      'Reusable across the entire Tyrolium ecosystem',
    ],
  },
  {
    slug: 'chatbox-twitch-framework',
    name: 'ChatBoxTwitch Framework',
    icon: 'ri-live-line',
    gradient: 'linear-gradient(135deg, #0533c8 0%, #bf0000 100%)',
    tagline: 'Framework PHP pour styliser les chatbox Streamlabs',
    taglineEn: 'PHP framework to style and host Streamlabs chat boxes',
    description: 'Framework PHP hébergé sur Apache/Nginx qui crée un environnement de personnalisation des chatbox Streamlabs en HTML/CSS/JS - conçu pour les talents d\'Influnias et Vturias.',
    descriptionEn: 'PHP framework hosted on Apache/Nginx that creates a customisation environment for Streamlabs chat boxes in HTML/CSS/JS - designed for Influnias and Vturias talents.',
    longDesc: `ChatBoxTwitch Framework est un framework PHP qui crée un environnement d'hébergement et de stylisation pour les chatbox Streamlabs. Une fois déployé sur un serveur Apache ou Nginx, il permet de personnaliser entièrement l'apparence du chat Twitch - messages, couleurs, animations, polices - via HTML, CSS et JavaScript. L'URL générée est ensuite intégrée directement comme source navigateur dans OBS ou Streamlabs. Conçu pour déployer rapidement des thèmes de chatbox sur mesure pour les streamers talents d'Influnias et de Vturias.`,
    longDescEn: `ChatBoxTwitch Framework is a PHP framework that creates a hosting and styling environment for Streamlabs chat boxes. Once deployed on an Apache or Nginx server, it allows full customisation of the Twitch chat appearance - messages, colours, animations, fonts - via HTML, CSS and JavaScript. The generated URL is then integrated directly as a browser source in OBS or Streamlabs. Designed to quickly deploy custom chat box themes for streamer talents at Influnias and Vturias.`,
    status: 'active',
    tech: ['PHP', 'HTML', 'CSS', 'JavaScript'],
    github: 'https://github.com/TheMaxium69/ChatBoxTheme-Template',
    usedBy: [
      { name: 'AuroreTVv', url: 'https://github.com/TheMaxium69/ChatBoxTheme-AuroreTVv' },
      { name: 'DoubleT',   url: 'https://github.com/TheMaxium69/ChatBoxTheme-DoubleT' },
    ],
    version: 'V1.0',
    contributors: ['Maxime Tournier'],
    features: [
      'Environnement d\'hébergement chatbox sur Apache/Nginx',
      'Personnalisation HTML/CSS/JS complète',
      'Compatible Streamlabs (source navigateur OBS)',
      'Thèmes de chat sur mesure par streamer',
      'Déploiement rapide de nouveaux thèmes',
      'Conçu pour les talents Influnias & Vturias',
    ],
    featuresEn: [
      'Chat box hosting environment on Apache/Nginx',
      'Full HTML/CSS/JS customisation',
      'Streamlabs compatible (OBS browser source)',
      'Per-streamer custom chat themes',
      'Fast deployment of new themes',
      'Designed for Influnias & Vturias talents',
    ],
  },
];

export function getLabBySlug(slug: string): Lab | undefined {
  return LABS.find(l => l.slug === slug);
}
