import { Component, ViewEncapsulation, inject, AfterViewInit, OnDestroy, NgZone } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TyroUiLangService } from 'tyrolium-ui';

export type EventStatus = 'past' | 'present' | 'future';

export interface TimelineEvent {
  date: string;
  dateEn: string;
  title: string;
  titleEn: string;
  description: string;
  descriptionEn: string;
  icon: string;
  status: EventStatus;
  tags?: string[];
}

@Component({
  selector: 'app-chronologie',
  templateUrl: './chronologie.html',
  styleUrls: ['./chronologie.css'],
  imports: [CommonModule],
  encapsulation: ViewEncapsulation.None,
})
export class Chronologie implements AfterViewInit, OnDestroy {

  readonly lang = inject(TyroUiLangService).lang;

  private observer?: IntersectionObserver;

  readonly events: TimelineEvent[] = [
    {
      date: '9 juillet 2017',
      dateEn: 'July 9, 2017',
      title: 'Création du projet',
      titleEn: 'Project creation',
      description: 'Imaginé comme un serveur Minecraft dit "PVP/Faction Moddé", c\'est le tout premier germe de ce qui deviendra Tyrolium.',
      descriptionEn: 'Conceived as a modded Minecraft PvP/Faction server - the very first seed of what would become Tyrolium.',
      icon: 'ri-rocket-2-fill',
      status: 'past',
      tags: ['Minecraft', 'Origine'],
    },
    {
      date: '12 juillet 2017',
      dateEn: 'July 12, 2017',
      title: 'Invention du nom "Tyrolium"',
      titleEn: 'The name "Tyrolium" is born',
      description: 'Le nom "Tyrolium" est une contraction de la "Tyrolite" et du "Paladium" - un minerais fictif créé pour le serveur Minecraft.',
      descriptionEn: '"Tyrolium" is a portmanteau of "Tyrolite" and "Palladium" - a fictional ore created for the Minecraft server.',
      icon: 'ri-lightbulb-fill',
      status: 'past',
      tags: ['Identité', 'Nom'],
    },
    {
      date: '5 mars 2018',
      dateEn: 'March 5, 2018',
      title: 'Début de la Bêta de TyroServ',
      titleEn: 'TyroServ Beta begins',
      description: 'Début de la version Bêta de TyroServ, marquant la fin du développement Alpha, avec un nouveau logo pour l\'occasion.',
      descriptionEn: 'Start of the TyroServ Beta, marking the end of the Alpha development phase, with a new logo.',
      icon: 'ri-server-fill',
      status: 'past',
      tags: ['TyroServ', 'Bêta'],
    },
    {
      date: '26 septembre 2018',
      dateEn: 'September 26, 2018',
      title: 'Bêta publique de TyroServ',
      titleEn: 'TyroServ public beta',
      description: 'Lancement d\'une version Bêta publique sous candidature, accompagnée d\'un nouveau logo.',
      descriptionEn: 'Launch of an application-based public Beta, with a new logo.',
      icon: 'ri-broadcast-fill',
      status: 'past',
      tags: ['TyroServ', 'Bêta'],
    },
    {
      date: '29 juillet 2019',
      dateEn: 'July 29, 2019',
      title: 'Création de Tyrolium Ent.',
      titleEn: 'Tyrolium Ent. founded',
      description: 'Transformation du projet en une entreprise multisectorielle baptisée "Tyrolium Entertainment".',
      descriptionEn: 'The project transforms into a multi-sector company named "Tyrolium Entertainment".',
      icon: 'ri-building-2-fill',
      status: 'past',
      tags: ['Corporate', 'Entreprise'],
    },
    {
      date: '1er août 2019',
      dateEn: 'August 1, 2019',
      title: 'Premier logo de l\'entreprise',
      titleEn: 'First company logo',
      description: 'Création du premier logo de l\'entreprise, qui durera presque 3 ans avant d\'être remplacé.',
      descriptionEn: 'Creation of the company\'s first logo, which lasted nearly 3 years before being replaced.',
      icon: 'ri-image-fill',
      status: 'past',
      tags: ['Design', 'Logo'],
    },
    {
      date: '17 octobre 2019',
      dateEn: 'October 17, 2019',
      title: 'Développement du TyroMod',
      titleEn: 'TyroMod development starts',
      description: 'Début du développement du TyroMod, l\'extension Minecraft utilisée pour modifier le jeu dans le projet TyroServ.',
      descriptionEn: 'Start of TyroMod development, the Minecraft extension used to modify the game within the TyroServ project.',
      icon: 'ri-code-box-fill',
      status: 'past',
      tags: ['Minecraft', 'Dev', 'TyroMod'],
    },
    {
      date: '15 novembre 2019',
      dateEn: 'November 15, 2019',
      title: 'Création de Wonderlium',
      titleEn: 'Wonderlium created',
      description: 'À l\'origine un projet appelé "Les Omegastar", racheté par Tyrolium et transformé en Wonderlium - un projet de vidéos sur l\'univers geek.',
      descriptionEn: 'Originally a project called "Les Omegastar", acquired by Tyrolium and reborn as Wonderlium - a geek culture video project.',
      icon: 'ri-film-fill',
      status: 'past',
      tags: ['Wonderlium', 'Geek'],
    },
    {
      date: '25 novembre 2019',
      dateEn: 'November 25, 2019',
      title: 'Première vidéo de Wonderlium',
      titleEn: 'Wonderlium\'s first video',
      description: 'Première vidéo du projet Wonderlium, consacrée à la console SNES.',
      descriptionEn: 'Wonderlium\'s first video, dedicated to the SNES console.',
      icon: 'ri-youtube-fill',
      status: 'past',
      tags: ['Wonderlium', 'Vidéo'],
    },
    {
      date: '5 décembre 2019',
      dateEn: 'December 5, 2019',
      title: 'Création de TyroMusic',
      titleEn: 'TyroMusic created',
      description: 'Création du projet TyroMusic avec sa charte graphique, dédié à la création musicale.',
      descriptionEn: 'Creation of TyroMusic with its brand guidelines, a project dedicated to music creation.',
      icon: 'ri-music-fill',
      status: 'past',
      tags: ['TyroMusic', 'Musique'],
    },
    {
      date: '22 mars 2020',
      dateEn: 'March 22, 2020',
      title: 'Lancement du site de Tyrolium Ent.',
      titleEn: 'Tyrolium Ent. website launch',
      description: 'Lancement de la première version du site internet de l\'entreprise.',
      descriptionEn: 'Launch of the company\'s first website.',
      icon: 'ri-global-fill',
      status: 'past',
      tags: ['Site', 'Web'],
    },
    {
      date: '23 mars 2020',
      dateEn: 'March 23, 2020',
      title: 'Création de Freenium',
      titleEn: 'Freenium created',
      description: 'Création du projet Freenium, projet de freelance qui n\'aboutira jamais vraiment - ancêtre des prestations.',
      descriptionEn: 'Creation of Freenium, a freelance project that never fully took off - the ancestor of our service offerings.',
      icon: 'ri-briefcase-fill',
      status: 'past',
      tags: ['Freenium', 'Freelance'],
    },
    {
      date: '25 mars 2020',
      dateEn: 'March 25, 2020',
      title: 'Nouveau logo pour TyroMusic',
      titleEn: 'New TyroMusic logo',
      description: 'Changement du logo du projet TyroMusic.',
      descriptionEn: 'New logo for the TyroMusic project.',
      icon: 'ri-palette-fill',
      status: 'past',
      tags: ['TyroMusic', 'Design'],
    },
    {
      date: '30 mars 2020',
      dateEn: 'March 30, 2020',
      title: 'Trailer de TyroServ',
      titleEn: 'TyroServ trailer',
      description: 'Trailer pour le lancement de TyroServ annonçant pour la première fois la date de sortie officielle du serveur.',
      descriptionEn: 'Trailer for the TyroServ launch, announcing the official release date for the first time.',
      icon: 'ri-youtube-fill',
      status: 'past',
      tags: ['TyroServ', 'Trailer'],
    },
    {
      date: '26 avril 2020',
      dateEn: 'April 26, 2020',
      title: 'Lancement de TyroServ',
      titleEn: 'TyroServ launch',
      description: 'Lancement officiel du serveur Minecraft avec le site, le launcher, le TyroMod et les maps.',
      descriptionEn: 'Official launch of the Minecraft server with the website, launcher, TyroMod and custom maps.',
      icon: 'ri-server-fill',
      status: 'past',
      tags: ['TyroServ', 'Lancement'],
    },
    {
      date: '29 avril 2020',
      dateEn: 'April 29, 2020',
      title: 'TyroServ atteint 4 000 joueurs',
      titleEn: 'TyroServ reaches 4,000 players',
      description: '4 jours seulement après la sortie, TyroServ atteint 4 000 joueurs uniques, avec 160 joueurs connectés en permanence en moyenne.',
      descriptionEn: 'Just 4 days after launch, TyroServ reaches 4,000 unique players with an average of 160 players online at all times.',
      icon: 'ri-group-fill',
      status: 'past',
      tags: ['TyroServ', 'Milestone'],
    },
    {
      date: '5 mai 2020',
      dateEn: 'May 5, 2020',
      title: 'Création de Gamenium',
      titleEn: 'Gamenium created',
      description: 'Création du projet Gamenium, site d\'actualité et de critique de jeux-vidéo.',
      descriptionEn: 'Creation of Gamenium, a video game news and review site.',
      icon: 'ri-newspaper-fill',
      status: 'past',
      tags: ['Gamenium', 'Gaming'],
    },
    {
      date: '18 mai 2020',
      dateEn: 'May 18, 2020',
      title: 'Création de TyroStudio',
      titleEn: 'TyroStudio created',
      description: 'Création du projet TyroStudio, studio de développement de jeux-vidéo.',
      descriptionEn: 'Creation of TyroStudio, a video game development studio.',
      icon: 'ri-gamepad-fill',
      status: 'past',
      tags: ['TyroStudio', 'Jeux-vidéo'],
    },
    {
      date: '24 mai 2020',
      dateEn: 'May 24, 2020',
      title: 'Lancement du site de Wonderlium',
      titleEn: 'Wonderlium website launch',
      description: 'Lancement du site du projet Wonderlium, dédié aux vidéos sur l\'univers geek.',
      descriptionEn: 'Launch of the Wonderlium website, dedicated to geek culture videos.',
      icon: 'ri-global-fill',
      status: 'past',
      tags: ['Wonderlium', 'Site'],
    },
    {
      date: '27 août 2020',
      dateEn: 'August 27, 2020',
      title: 'Lancement de la boutique',
      titleEn: 'Shop launch',
      description: 'Lancement de la boutique de Tyrolium et création du projet TyroShop.',
      descriptionEn: 'Launch of the Tyrolium shop and creation of the TyroShop project.',
      icon: 'ri-store-fill',
      status: 'past',
      tags: ['TyroShop', 'Boutique'],
    },
    {
      date: '28 août 2020',
      dateEn: 'August 28, 2020',
      title: 'Logo de TyroStudio',
      titleEn: 'TyroStudio logo',
      description: 'Création du premier logo de TyroStudio représentant un phoenix - symbole resté mystérieux.',
      descriptionEn: 'Creation of TyroStudio\'s first logo featuring a phoenix - a symbol that remained shrouded in mystery.',
      icon: 'ri-image-fill',
      status: 'past',
      tags: ['TyroStudio', 'Logo'],
    },
    {
      date: '31 août 2020',
      dateEn: 'August 31, 2020',
      title: 'Deuxième vidéo de Wonderlium',
      titleEn: 'Wonderlium\'s second video',
      description: 'Deuxième vidéo du projet Wonderlium, consacrée à la GameCube.',
      descriptionEn: 'Wonderlium\'s second video, dedicated to the GameCube.',
      icon: 'ri-youtube-fill',
      status: 'past',
      tags: ['Wonderlium', 'Vidéo'],
    },
    {
      date: '4 septembre 2020',
      dateEn: 'September 4, 2020',
      title: 'TyroServ atteint 10 000 joueurs',
      titleEn: 'TyroServ reaches 10,000 players',
      description: 'Après 5 mois de fonctionnement, TyroServ atteint le cap des 10 000 joueurs uniques.',
      descriptionEn: 'After 5 months of operation, TyroServ reaches the milestone of 10,000 unique players.',
      icon: 'ri-trophy-fill',
      status: 'past',
      tags: ['TyroServ', 'Milestone'],
    },
    {
      date: '21 janvier 2021',
      dateEn: 'January 21, 2021',
      title: 'Fermeture de Freenium',
      titleEn: 'Freenium closes',
      description: 'Fermeture du projet Freenium, qui n\'avait jamais vraiment démarré et qui restera l\'ancêtre des prestations.',
      descriptionEn: 'Closure of Freenium, which never fully launched and remains the ancestor of our service offerings.',
      icon: 'ri-close-circle-fill',
      status: 'past',
      tags: ['Freenium', 'Fermeture'],
    },
    {
      date: '23 janvier 2021',
      dateEn: 'January 23, 2021',
      title: 'Logo de TyroShop',
      titleEn: 'TyroShop logo',
      description: 'Création du logo de la boutique TyroShop, désormais considéré comme un projet à part entière.',
      descriptionEn: 'Creation of the TyroShop logo, now considered a full project in its own right.',
      icon: 'ri-store-fill',
      status: 'past',
      tags: ['TyroShop', 'Logo'],
    },
    {
      date: '21 février 2021',
      dateEn: 'February 21, 2021',
      title: 'Fermeture de la saison 1 de TyroServ',
      titleEn: 'TyroServ season 1 closes',
      description: 'Fermeture du serveur TyroServ, initialement pensée comme la fin définitive du projet.',
      descriptionEn: 'Closure of the TyroServ server, initially thought to be the definitive end of the project.',
      icon: 'ri-server-fill',
      status: 'past',
      tags: ['TyroServ', 'S1', 'Fermeture'],
    },
    {
      date: '14 mai 2021',
      dateEn: 'May 14, 2021',
      title: 'TyroServ S1 en open-source',
      titleEn: 'TyroServ S1 goes open-source',
      description: 'Suite à la fermeture, le code de la saison 1 de TyroServ est rendu open-source et libre au public.',
      descriptionEn: 'Following the closure, TyroServ season 1\'s code is open-sourced and made freely available.',
      icon: 'ri-git-branch-fill',
      status: 'past',
      tags: ['TyroServ', 'Open-Source'],
    },
    {
      date: '25 mai 2021',
      dateEn: 'May 25, 2021',
      title: 'Annonce de la saison 2 de TyroServ',
      titleEn: 'TyroServ season 2 announced',
      description: 'Après quelques mois d\'abandon, annonce officielle de la reprise du projet avec une date de sortie pour la saison 2.',
      descriptionEn: 'After a few months on hold, official announcement of the project\'s return with a release date for season 2.',
      icon: 'ri-broadcast-fill',
      status: 'past',
      tags: ['TyroServ', 'S2', 'Annonce'],
    },
    {
      date: '28 mai 2021',
      dateEn: 'May 28, 2021',
      title: 'Lancement de la saison 2 de TyroServ',
      titleEn: 'TyroServ season 2 launch',
      description: 'Lancement de la saison 2 avec un nouveau launcher, un nouveau site, de nouveaux plugins et une stabilité serveur accrue.',
      descriptionEn: 'Season 2 launches with a new launcher, website, plugins and improved server stability.',
      icon: 'ri-server-fill',
      status: 'past',
      tags: ['TyroServ', 'S2'],
    },
    {
      date: '2 juin 2021',
      dateEn: 'June 2, 2021',
      title: 'Lancement de Gamenium',
      titleEn: 'Gamenium launch',
      description: 'Lancement officiel de Gamenium avec des actualités gaming sur Instagram et Discord, et un nouveau logo.',
      descriptionEn: 'Official launch of Gamenium with gaming news on Instagram and Discord, and a new logo.',
      icon: 'ri-newspaper-fill',
      status: 'past',
      tags: ['Gamenium', 'Lancement'],
    },
    {
      date: '21 juillet 2021',
      dateEn: 'July 21, 2021',
      title: 'Création de TyroDiscord',
      titleEn: 'TyroDiscord created',
      description: 'Création du projet TyroDiscord, dédié aux bots et logiciels pour améliorer l\'expérience Discord.',
      descriptionEn: 'Creation of TyroDiscord, dedicated to bots and software to enhance the Discord experience.',
      icon: 'ri-discord-fill',
      status: 'past',
      tags: ['TyroDiscord', 'Discord'],
    },
    {
      date: '25 juillet 2021',
      dateEn: 'July 25, 2021',
      title: 'Lancement du TyroBot et TyroServBot',
      titleEn: 'TyroBot and TyroServBot launch',
      description: 'Lancement des deux premiers bots Discord publics : un bot d\'amélioration de serveur et un bot reliant Minecraft à Discord.',
      descriptionEn: 'Launch of the first two public Discord bots: a server enhancement bot and a Minecraft-Discord bridge bot.',
      icon: 'ri-robot-fill',
      status: 'past',
      tags: ['TyroDiscord', 'Bot'],
    },
    {
      date: '20 août 2021',
      dateEn: 'August 20, 2021',
      title: 'Trailer du nouveau logo',
      titleEn: 'New logo trailer',
      description: 'Trailer diffusé sur tous les réseaux de Tyrolium, dévoilant pour la première fois le nouveau logo de l\'entreprise.',
      descriptionEn: 'Trailer shared across all Tyrolium channels, revealing the company\'s new logo for the first time.',
      icon: 'ri-youtube-fill',
      status: 'past',
      tags: ['Identité', 'Trailer'],
    },
    {
      date: '21 août 2021',
      dateEn: 'August 21, 2021',
      title: 'Nouveau logo · Tyrolium Entertainment → Tyrolium',
      titleEn: 'New logo · Tyrolium Entertainment → Tyrolium',
      description: 'Après trois ans, Tyrolium adopte un logo moderne et passe de "Tyrolium Entertainment" à simplement "Tyrolium".',
      descriptionEn: 'After three years, Tyrolium adopts a modern logo and renames from "Tyrolium Entertainment" to simply "Tyrolium".',
      icon: 'ri-palette-fill',
      status: 'past',
      tags: ['Identité', 'Rebranding', 'Logo'],
    },
    {
      date: '23 août 2021',
      dateEn: 'August 23, 2021',
      title: 'TyroMusic devient Sélémusium',
      titleEn: 'TyroMusic becomes Sélémusium',
      description: 'TyroMusic change entièrement de nom pour devenir Sélémusium, avec une toute nouvelle charte graphique.',
      descriptionEn: 'TyroMusic fully rebrands as Sélémusium, with a brand new visual identity.',
      icon: 'ri-music-fill',
      status: 'past',
      tags: ['Sélémusium', 'Rebranding'],
    },
    {
      date: '24 août 2021',
      dateEn: 'August 24, 2021',
      title: 'Lancement des prestations',
      titleEn: 'Services launch',
      description: 'Lancement des prestations de Tyrolium : création de sites Web et services liés à Minecraft.',
      descriptionEn: 'Launch of Tyrolium\'s professional services: web development and Minecraft-related services.',
      icon: 'ri-tools-fill',
      status: 'past',
      tags: ['Prestations', 'Web', 'Minecraft'],
    },
    {
      date: '10 août 2021',
      dateEn: 'August 10, 2021',
      title: 'Changement de logo pour 3 projets',
      titleEn: '3 projects get new logos',
      description: 'Changement simultané des logos de Wonderlium, Sélémusium et TyroShop.',
      descriptionEn: 'Simultaneous logo update for Wonderlium, Sélémusium and TyroShop.',
      icon: 'ri-palette-fill',
      status: 'past',
      tags: ['Design', 'Logo'],
    },
    {
      date: '14 novembre 2021',
      dateEn: 'November 14, 2021',
      title: 'Lancement du site Status Server',
      titleEn: 'Status Server website launch',
      description: 'Lancement du site permettant de suivre en temps réel la stabilité de tous les services et serveurs de Tyrolium.',
      descriptionEn: 'Launch of the site for real-time monitoring of all Tyrolium services and servers.',
      icon: 'ri-pulse-fill',
      status: 'past',
      tags: ['Infrastructure', 'Status'],
    },
    {
      date: '22 novembre 2021',
      dateEn: 'November 22, 2021',
      title: 'Lancement du site de Sélémusium',
      titleEn: 'Sélémusium website launch',
      description: 'Lancement du site de présentation du projet musical Sélémusium.',
      descriptionEn: 'Launch of the Sélémusium music project website.',
      icon: 'ri-global-fill',
      status: 'past',
      tags: ['Sélémusium', 'Site'],
    },
    {
      date: '4 janvier 2022',
      dateEn: 'January 4, 2022',
      title: 'Deuxième version du site Tyrolium',
      titleEn: 'Tyrolium website v2',
      description: 'Lancement de la deuxième version du site de Tyrolium, entièrement refondu à zéro.',
      descriptionEn: 'Launch of Tyrolium\'s second website, rebuilt entirely from scratch.',
      icon: 'ri-global-fill',
      status: 'past',
      tags: ['Site', 'Web', 'Refonte'],
    },
    {
      date: '8 janvier 2022',
      dateEn: 'January 8, 2022',
      title: 'Création du projet Duo-Gramme',
      titleEn: 'Duo-Gramme project created',
      description: 'Projet de contenus divertissants et informatifs sur les réseaux sociaux, en collaboration avec l\'entreprise MA3WAN.',
      descriptionEn: 'An entertainment and informational content project on social media, in collaboration with MA3WAN.',
      icon: 'ri-team-fill',
      status: 'past',
      tags: ['Duo-Gramme', 'Réseaux Sociaux'],
    },
    {
      date: '24 mars 2022',
      dateEn: 'March 24, 2022',
      title: 'Création du projet SolidServ',
      titleEn: 'SolidServ project created',
      description: 'Création du projet SolidServ, hébergeur de serveurs de jeux, de sites internet et bien plus.',
      descriptionEn: 'Creation of SolidServ, a hosting provider for game servers, websites and more.',
      icon: 'ri-cloud-fill',
      status: 'past',
      tags: ['SolidServ', 'Hébergement'],
    },
    {
      date: '2 mai 2022',
      dateEn: 'May 2, 2022',
      title: 'Lancement du site de TyroDiscord',
      titleEn: 'TyroDiscord website launch',
      description: 'Lancement du site de présentation du projet TyroDiscord.',
      descriptionEn: 'Launch of the TyroDiscord presentation website.',
      icon: 'ri-discord-fill',
      status: 'past',
      tags: ['TyroDiscord', 'Site'],
    },
    {
      date: '7 mai 2022',
      dateEn: 'May 7, 2022',
      title: 'Lancement de SolidServ',
      titleEn: 'SolidServ launch',
      description: 'Lancement officiel du site et des serveurs de SolidServ.',
      descriptionEn: 'Official launch of the SolidServ website and servers.',
      icon: 'ri-server-fill',
      status: 'past',
      tags: ['SolidServ', 'Lancement'],
    },
    {
      date: '20 mai 2022',
      dateEn: 'May 20, 2022',
      title: 'Nouveau logo pour Sélémusium',
      titleEn: 'New Sélémusium logo',
      description: 'Nouveau changement du logo du projet musical Sélémusium.',
      descriptionEn: 'Another new logo for the Sélémusium music project.',
      icon: 'ri-palette-fill',
      status: 'past',
      tags: ['Sélémusium', 'Logo'],
    },
    {
      date: '20 mai 2022',
      dateEn: 'May 20, 2022',
      title: 'Création du projet TyroStudent',
      titleEn: 'TyroStudent created',
      description: 'Création du projet de formation de Tyrolium, TyroStudent.',
      descriptionEn: 'Creation of TyroStudent, Tyrolium\'s training and education project.',
      icon: 'ri-book-open-fill',
      status: 'past',
      tags: ['TyroStudent', 'Formation'],
    },
    {
      date: '9 juillet 2022',
      dateEn: 'July 9, 2022',
      title: 'Vidéo des 5 ans de Tyrolium',
      titleEn: 'Tyrolium 5th anniversary video',
      description: 'Tyrolium réalise une vidéo d\'animation pour ses 5 ans retraçant toute son histoire.',
      descriptionEn: 'Tyrolium releases an animated video for its 5th anniversary, retracing its entire history.',
      icon: 'ri-cake-fill',
      status: 'past',
      tags: ['5 Ans', 'Anniversaire'],
    },
    {
      date: '9 juillet 2022',
      dateEn: 'July 9, 2022',
      title: 'Annonce de la saison 3 de TyroServ',
      titleEn: 'TyroServ season 3 announced',
      description: 'Lors de la vidéo des 5 ans, annonce de la saison 3 de TyroServ avec un teaser et un nouveau logo.',
      descriptionEn: 'During the 5th anniversary video, TyroServ season 3 is announced with a teaser and new logo.',
      icon: 'ri-server-fill',
      status: 'past',
      tags: ['TyroServ', 'S3', 'Annonce'],
    },
    {
      date: '9 juillet 2022',
      dateEn: 'July 9, 2022',
      title: 'Annonce du premier album de Sélémusium',
      titleEn: 'Sélémusium\'s debut album announced',
      description: 'Lors de la vidéo des 5 ans, Sélémusium annonce avec un trailer son premier album "Artomyx".',
      descriptionEn: 'During the 5th anniversary video, Sélémusium announces its debut album "Artomyx" with a trailer.',
      icon: 'ri-music-fill',
      status: 'past',
      tags: ['Sélémusium', 'Artomyx'],
    },
    {
      date: '9 juillet 2022',
      dateEn: 'July 9, 2022',
      title: 'Annonce des comptes Useritium',
      titleEn: 'Useritium accounts announced',
      description: 'Lors de la vidéo des 5 ans, annonce du lancement des comptes Useritium.',
      descriptionEn: 'During the 5th anniversary video, the launch of Useritium accounts is announced.',
      icon: 'ri-user-fill',
      status: 'past',
      tags: ['Useritium', 'Annonce'],
    },
    {
      date: '9 juillet 2022',
      dateEn: 'July 9, 2022',
      title: 'Lancement du site TyroBirthday',
      titleEn: 'TyroBirthday website launch',
      description: 'Pour les 5 ans de Tyrolium, lancement d\'un site événementiel dédié à l\'occasion.',
      descriptionEn: 'For Tyrolium\'s 5th anniversary, launch of a dedicated event website.',
      icon: 'ri-gift-fill',
      status: 'past',
      tags: ['5 Ans', 'Site'],
    },
    {
      date: '11 juillet 2022',
      dateEn: 'July 11, 2022',
      title: 'Lancement du premier album de Sélémusium',
      titleEn: 'Sélémusium\'s debut album released',
      description: 'Sélémusium sort son premier album "Artomyx" sur toutes les plateformes de streaming.',
      descriptionEn: 'Sélémusium releases its debut album "Artomyx" on all streaming platforms.',
      icon: 'ri-music-fill',
      status: 'past',
      tags: ['Sélémusium', 'Artomyx', 'Album'],
    },
    {
      date: '13 juillet 2022',
      dateEn: 'July 13, 2022',
      title: 'Lancement des animations',
      titleEn: 'Animations launch',
      description: 'Tyrolium publie une animation présentant l\'ensemble de ses projets, disponible sur la page projets.',
      descriptionEn: 'Tyrolium releases an animation presenting all its projects, available on the projects page.',
      icon: 'ri-film-fill',
      status: 'past',
      tags: ['Animation', 'Communication'],
    },
    {
      date: '15 juillet 2022',
      dateEn: 'July 15, 2022',
      title: 'Reboot de Wonderlium',
      titleEn: 'Wonderlium reboot',
      description: 'Reboot de Wonderlium et reprise des vidéos régulières avec une nouvelle charte graphique.',
      descriptionEn: 'Wonderlium reboot with regular videos resuming under a new visual identity.',
      icon: 'ri-film-fill',
      status: 'past',
      tags: ['Wonderlium', 'Reboot'],
    },
    {
      date: '15 juillet 2022',
      dateEn: 'July 15, 2022',
      title: 'Troisième vidéo de Wonderlium',
      titleEn: 'Wonderlium\'s third video',
      description: 'Troisième vidéo du projet Wonderlium, sur la naissance du jeu-jouet.',
      descriptionEn: 'Wonderlium\'s third video, on the birth of the toy video game.',
      icon: 'ri-youtube-fill',
      status: 'past',
      tags: ['Wonderlium', 'Vidéo'],
    },
    {
      date: '27 septembre 2022',
      dateEn: 'September 27, 2022',
      title: 'Création d\'Influnias',
      titleEn: 'Influnias created',
      description: 'Création de l\'agence de portage d\'influenceurs Influnias, avec son logo et sa charte graphique.',
      descriptionEn: 'Creation of Influnias, the influencer agency, with its logo and brand guidelines.',
      icon: 'ri-megaphone-fill',
      status: 'past',
      tags: ['Influnias', 'Agence'],
    },
    {
      date: '13 janvier 2023',
      dateEn: 'January 13, 2023',
      title: 'Restructuration totale de la holding',
      titleEn: 'Full holding restructuring',
      description: 'Restructuration totale de Tyrolium : réduction des effectifs et recentrage sur les projets stratégiques. Seuls TyroServ, Influnias, SolidServ, TyroStudio et Gamenium sont maintenus.',
      descriptionEn: 'Full restructuring of Tyrolium: workforce reduction and refocus on core strategic projects. Only TyroServ, Influnias, SolidServ, TyroStudio and Gamenium are retained.',
      icon: 'ri-restart-fill',
      status: 'past',
      tags: ['Corporate', 'Restructuration'],
    },
    {
      date: 'Avril 2023',
      dateEn: 'April 2023',
      title: 'Création de Vturias',
      titleEn: 'Vturias created',
      description: 'Création de Vturias, nouveau projet de Tyrolium dédié à l\'univers des VTubers.',
      descriptionEn: 'Creation of Vturias, a new Tyrolium project dedicated to the VTuber world.',
      icon: 'ri-live-fill',
      status: 'past',
      tags: ['Vturias', 'VTuber'],
    },
    {
      date: '22 mai 2023',
      dateEn: 'May 22, 2023',
      title: 'Lancement des prestations de formation',
      titleEn: 'Training services launch',
      description: 'Lancement des prestations de formation de Tyrolium : cours de développement informatique, DevOps et administration système.',
      descriptionEn: 'Launch of Tyrolium\'s training services: programming courses, DevOps and system administration.',
      icon: 'ri-book-open-fill',
      status: 'past',
      tags: ['Formation', 'Dev', 'DevOps'],
    },
    {
      date: '9 juillet 2023',
      dateEn: 'July 9, 2023',
      title: 'Vidéo des 6 ans de Tyrolium',
      titleEn: 'Tyrolium 6th anniversary video',
      description: 'Tyrolium réalise une vidéo retraçant toute l\'histoire de l\'entreprise pour ses 6 ans.',
      descriptionEn: 'Tyrolium releases a video retracing the entire history of the company for its 6th anniversary.',
      icon: 'ri-cake-fill',
      status: 'past',
      tags: ['6 Ans', 'Anniversaire'],
    },
    {
      date: '11 août 2023',
      dateEn: 'August 11, 2023',
      title: 'Lancement de la saison 2.5 de TyroServ',
      titleEn: 'TyroServ season 2.5 launch',
      description: 'Lancement de la saison 2.5 de TyroServ, une mise à jour majeure entre deux saisons complètes.',
      descriptionEn: 'Launch of TyroServ season 2.5, a major update bridging two full seasons.',
      icon: 'ri-server-fill',
      status: 'past',
      tags: ['TyroServ', 'S2.5'],
    },
    {
      date: '2 octobre 2023',
      dateEn: 'October 2, 2023',
      title: 'Ouverture des locaux à Villeurbanne',
      titleEn: 'Office opens in Villeurbanne',
      description: 'Ouverture du premier établissement physique de Tyrolium, situé à Villeurbanne, France.',
      descriptionEn: 'Opening of Tyrolium\'s first physical office, located in Villeurbanne, France.',
      icon: 'ri-building-fill',
      status: 'past',
      tags: ['Corporate', 'Locaux'],
    },
    {
      date: 'Novembre 2023',
      dateEn: 'November 2023',
      title: 'Création de NexiumiaCRM',
      titleEn: 'NexiumiaCRM created',
      description: 'Création de NexiumiaCRM, solution CRM développée en interne par Tyrolium.',
      descriptionEn: 'Creation of NexiumiaCRM, a CRM solution developed in-house by Tyrolium.',
      icon: 'ri-contacts-fill',
      status: 'past',
      tags: ['NexiumiaCRM', 'CRM'],
    },
    {
      date: '21 janvier 2024',
      dateEn: 'January 21, 2024',
      title: 'Lancement public de Vturias',
      titleEn: 'Vturias public launch',
      description: 'Lancement officiel et public de Vturias, ouvrant la plateforme à tous.',
      descriptionEn: 'Official public launch of Vturias, opening the platform to everyone.',
      icon: 'ri-live-fill',
      status: 'past',
      tags: ['Vturias', 'Lancement'],
    },
    {
      date: 'Avril 2024',
      dateEn: 'April 2024',
      title: 'Création du projet Avra',
      titleEn: 'Avra project created',
      description: 'Création d\'Avra, une offre d\'accompagnement tout-en-un pour les entreprises : marketing, communication et tech réunis dans une formule d\'abonnement unique.',
      descriptionEn: 'Creation of Avra, an all-in-one subscription service for businesses combining marketing, communication and tech support in a single package.',
      icon: 'ri-sparkling-fill',
      status: 'past',
      tags: ['Avra', 'Entreprise', 'Abonnement'],
    },
    {
      date: '9 juillet 2024',
      dateEn: 'July 9, 2024',
      title: 'Premier trailer de TyroServ S3 · 7 ans de Tyrolium',
      titleEn: 'First TyroServ S3 trailer · Tyrolium turns 7',
      description: 'Pour les 7 ans de Tyrolium, dévoilement du premier trailer officiel de la saison 3 de TyroServ.',
      descriptionEn: 'For Tyrolium\'s 7th anniversary, the first official trailer for TyroServ season 3 is revealed.',
      icon: 'ri-server-fill',
      status: 'past',
      tags: ['TyroServ', 'S3', 'Trailer', '7 Ans'],
    },
    {
      date: '25 juillet 2024',
      dateEn: 'July 25, 2024',
      title: 'Lancement de Useritium V2',
      titleEn: 'Useritium V2 launch',
      description: 'Lancement de la version 2 d\'Useritium, refonte majeure de la plateforme de comptes universels français.',
      descriptionEn: 'Launch of Useritium version 2, a major overhaul of the universal French accounts platform.',
      icon: 'ri-user-fill',
      status: 'past',
      tags: ['Useritium', 'V2', 'Lancement'],
    },
    {
      date: '16 octobre 2024',
      dateEn: 'October 16, 2024',
      title: 'Déménagement vers les nouveaux locaux',
      titleEn: 'Move to new offices',
      description: 'Tyrolium déménage dans ses deuxièmes locaux, toujours situés à Villeurbanne, France.',
      descriptionEn: 'Tyrolium moves into its second offices, still located in Villeurbanne, France.',
      icon: 'ri-building-fill',
      status: 'past',
      tags: ['Corporate', 'Locaux'],
    },
    {
      date: '21 décembre 2024',
      dateEn: 'December 21, 2024',
      title: 'Lancement de la bêta de Gamenium',
      titleEn: 'Gamenium beta launch',
      description: 'Lancement de la version bêta de Gamenium, ouvrant la plateforme à ses premiers utilisateurs tests.',
      descriptionEn: 'Launch of the Gamenium beta, opening the platform to its first test users.',
      icon: 'ri-newspaper-fill',
      status: 'past',
      tags: ['Gamenium', 'Bêta', 'Lancement'],
    },
    {
      date: '11 février 2025',
      dateEn: 'February 11, 2025',
      title: 'Lancement de Gamenium v1',
      titleEn: 'Gamenium v1 launch',
      description: 'Lancement officiel de la version 1 de Gamenium, après plusieurs mois de bêta.',
      descriptionEn: 'Official launch of Gamenium version 1, after several months of beta testing.',
      icon: 'ri-newspaper-fill',
      status: 'past',
      tags: ['Gamenium', 'Lancement', 'v1'],
    },
    {
      date: 'Mars 2025',
      dateEn: 'March 2025',
      title: 'Nouveau logo de TyroStudio',
      titleEn: 'New TyroStudio logo',
      description: 'TyroStudio adopte un nouveau logo, refonte de son identité visuelle.',
      descriptionEn: 'TyroStudio adopts a new logo, refreshing its visual identity.',
      icon: 'ri-palette-fill',
      status: 'past',
      tags: ['TyroStudio', 'Logo', 'Design'],
    },
    {
      date: 'Avril 2025',
      dateEn: 'April 2025',
      title: 'Fermeture du projet Avra',
      titleEn: 'Avra project closes',
      description: 'Fermeture du projet Avra, un an après sa création.',
      descriptionEn: 'Closure of the Avra project, one year after its creation.',
      icon: 'ri-close-circle-fill',
      status: 'past',
      tags: ['Avra', 'Fermeture'],
    },
    {
      date: '9 juillet 2025',
      dateEn: 'July 9, 2025',
      title: 'Vidéo des 8 ans de Tyrolium',
      titleEn: 'Tyrolium 8th anniversary video',
      description: 'Tyrolium réalise une vidéo retraçant toute l\'histoire de l\'entreprise pour ses 8 ans.',
      descriptionEn: 'Tyrolium releases a video retracing the entire history of the company for its 8th anniversary.',
      icon: 'ri-cake-fill',
      status: 'past',
      tags: ['8 Ans', 'Anniversaire'],
    },
    {
      date: '15 avril 2026',
      dateEn: 'April 15, 2026',
      title: 'TyroStudio devient TyroCiel',
      titleEn: 'TyroStudio becomes TyroCiel',
      description: 'TyroStudio change de nom pour devenir TyroCiel - un hommage à Loriciel, légendaire studio français de jeux-vidéo des années 80-90.',
      descriptionEn: 'TyroStudio rebrands as TyroCiel - a tribute to Loriciel, the legendary French video game studio of the 80s and 90s.',
      icon: 'ri-gamepad-fill',
      status: 'past',
      tags: ['TyroCiel', 'Rebranding', 'Loriciel'],
    },
    {
      date: 'Juillet 2026',
      dateEn: 'July 2026',
      title: 'Refonte totale du design system · 9 ans',
      titleEn: 'Full design system overhaul · 9th anniversary',
      description: 'Pour les 9 ans de Tyrolium, refonte complète de l\'identité visuelle : nouveau design system, nouveaux logos et nouvelle charte graphique pour Tyrolium et l\'ensemble de ses filiales.',
      descriptionEn: 'For Tyrolium\'s 9th anniversary, a complete visual identity overhaul: new design system, new logos and new brand guidelines for Tyrolium and all its subsidiaries.',
      icon: 'ri-palette-fill',
      status: 'future',
      tags: ['Design', 'Branding', '9 Ans'],
    },
  ];

  constructor(private ngZone: NgZone) {}

  ngAfterViewInit(): void {
    this.ngZone.runOutsideAngular(() => {
      this.observer = new IntersectionObserver(
        (entries) => {
          entries.forEach(entry => {
            if (entry.isIntersecting) {
              entry.target.classList.add('tl-visible');
            }
          });
        },
        { threshold: 0.15, rootMargin: '0px 0px -60px 0px' }
      );
      document.querySelectorAll('.tl-item').forEach(el => this.observer!.observe(el));
    });
  }

  ngOnDestroy(): void {
    this.observer?.disconnect();
  }
}
